### PR TITLE
Added matrix tutorial.

### PR DESCRIPTION
**Pull request by el3ctr0lyte**
I adapted DenshiVideo's matrix tutorial.

### CODE REVIEW

**Comment by el3ctr0lyte** [comment]
Luke, i know you have concerns over matrix. I think that you can easily avoid them by setting up your own identity server and adding matrix.org and vector.im to synapse's ip-blacklist. I didn't add it here, but maybe someone else can.

**Comment by LukeSmithxyz** [comment]
Are those `default_server` settings supposed to be there? Isn't that unnecessary and potentially crash-inducing if set in another config? I might not know better, I haven't tried these directions yet.

This instructional doesn't match the formatting of all others. example.com should be in <strong> and used in all cases (not YOUR_DOMAIN or anything), sudo should not be used.

**Comment by el3ctr0lyte** [comment]
Sorry about the YOUR_DOMAIN. I missed that one. As i said i basically copied it(with permission) from DenshiVideo. I didn't think of the sudos and have fixed them. As far as i know `default_server` shouldn't cause problems. Someone else should comment one this.

**Review by DGKSK8LIFE — APPROVED** [review]

**Comment by LukeSmithxyz** [comment]
As suspected, default_server breaks it. Couple other problems as well. Don't submit things you haven't tried. I'll do this myself.

**Pull request closed without merging**
