### PR TITLE
Managing a website with Git

### PR DESCRIPTION
**Pull request by valentino1337butiusegitlab**

### CODE REVIEW

**Comment by valentino1337butiusegitlab** [comment]
I made a tutorial on how to manage your site files using Git remote repos. Very useful. Excuse the messy HTML, i tried to follow the guidelines, but I made this site using pandoc and markdown. The original version of this tutorial is on [my website](https://valkun.xyz) with different example url and such minor changes.
This is very useful

**Comment by LukeSmithxyz** [comment]
Fix the HTML.

**Comment by valentino1337butiusegitlab** [comment]
daddy luke responded! of course

**Comment by valentino1337butiusegitlab** [comment]
fixed

**Review by DGKSK8LIFE — APPROVED** [review]

**Comment by LukeSmithxyz** [comment]
You didn't fix anything. Use the template page. I don't know what all these `<br />`s are for. Use the `main` tag. Use actual paragraph tags. Look at the page looks like before you resubmit it and make sure it actually looks like the others.

**Comment by LukeSmithxyz** [comment]
Also, use relative links of course.

**Comment by valentino1337butiusegitlab** [comment]
third times the charm

**Comment by termermc** [comment]
> (excuse the cringe, im a zoomer)

Are you serious man? Just don't say it, age doesn't factor into it

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tfasano1** [comment]
@valentino1337butiusegitlab Quit while your ahead kid, aren't you feeding your "code" to the machine?

**Comment by JacksonTaylorxyz** [comment]
This is the script I use for this purpose. I'd suggest using this instead, because this will only deploy when you push to the master branch, where as yours will deploy anytime you push to any branch (I'm pretty sure), which may not always be what you want.
```
#!/bin/bash
TARGET="/var/www/exampleSite"
GIT_DIR="/path/to/git/repo"
BRANCH="master"

while read oldrev newrev ref
do
	if [ "$ref" = "refs/heads/$BRANCH" ];
	then
		echo "Ref received. deploying..."
		git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
	else
		echo "Not on $BRANCH, will not be deploying."
	fi
done
```

**Pull request closed without merging**
