### PR TITLE
Added i2p site tutorial

### PR DESCRIPTION
**Pull request by qorg11**

### CODE REVIEW

**Comment by tenseoverflow** [comment]
Fantastic guide. Wanted to do something like this after Mentaloutlaw's video on it.

**Comment by LukeSmithxyz** [comment]
Is there an easier way of getting the hostname? I think if you're going to tell people to use a browser, you should probably assume that most people will think Mozilla Firefox on a local computer.

I don't know anything about i2p so I don't know myself. Or I should ask, is the hostname the publicly identifiable string i.e. like a URL? I legitimately don't know.

**Comment by qorg11** [comment]
You can get the hostname using this command: `printf "%s.b32.i2p" $(head -c 391 yourkey.dat |sha256sum|xxd -r -p | base32 |sed  s/=//g | tr A-Z a-z)`

**Comment by qorg11** [comment]
I added the guide of how to get the hostname using that command

**Comment by phirecc** [comment]
You forgot to close a code tag

**Comment by qorg11** [comment]
thanks, i fixed it

**Comment by qorg11** [comment]
bump¿

**Comment by LukeSmithxyz** [comment]
I had tested this out once a couple days ago and it wasn't immediately working for me. I'll try it again when I have the time. Been busy. I'm not really familiar with i2p anyway, but once I can verify it works, I will merge it.

**Comment by LukeSmithxyz** [comment]
Finally got around to adding this.

**Pull request merged**
