### PR TITLE
Added return 301 for www (hugo edition)

### PR DESCRIPTION
**Pull request by tomhonour**

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
I did finally try this and the lack of certbot errors doesn't mean much when it doesn't work in the first place. Nginx doesn't know how to direct host requests or something.

I've set this up with `www.lukesmith.xyz`---with or without HTTPS, it directs to based.cooking, which is hosted on the same server. Note that this happens for me in Firefox, but in Ungoogled Chromium, it directs to `lukesmith.xyz`.

**Comment by LukeSmithxyz** [comment]
I think that previous error was caused by browser cache. It's directing properly now.

The issue I am still uncomfortable with is that there should be a clean way to rewrite all requests of all `www.` domains to the proper host and include it either in a separate site file or in the NginX configuration. I definitely think it's stupid to have to get HTTPS for all these `www.` domains, but frankly that might be a necessity because if you go to a https address, you can't expect your browser to not throw a fit if someone 301s you to a different domain.

I'll think about this, but if I can't find a solution I like better, I'll add it.

**Comment by tomhonour** [comment]
In that case I think it would be best to use some regex like so...:
```
server {
	server_name "~(^www\.)?(?<domain>.+)$" ;
	return 301 $scheme://$domain$request_uri ;
}
```

... and then generating a certificate without appending `site-available\*` (I can't find the certbot flag but I think something alongside -d would be good).

The above regex has the benefit of also redirecting sub-domains.

**Comment by LukeSmithxyz** [comment]
I meant a separate Nginx file that deals with all redirect cases. I definitely do not want an entire article on this on the website. It is not important enough to warrant that.

It seems that the two code blocks you have do work for this at least. I will make the changes myself and add them to the Nginx tweaks article.

**Comment by LukeSmithxyz** [comment]
My mistake, it's not working. Yeah screw this. I'm just going to tell people to create a ALIAS record and get an expanded certificate if they want. That's how it really should be done anyway.

**Pull request closed without merging**
