### PR TITLE
Page quality guide

### PR DESCRIPTION
**Pull request by mccorxyz**
When following the landchad guide or video tutorials, newbies may not know about the below features that improve either performance or SEO.

This guide walks people through the process of:
- using web.dev/measure to audit their sites performance
- setting nginx server up for caching image and CSS files
- enabling text compression for nginx server
- properly sizing images (using cwebp)
- using alt attributes for images
- adding meta tags for SEO

### CODE REVIEW

**Comment by tfasano1** [comment]
Doubt this will be merged because of the twitter/facebook seo stuff, but image codecs like webp and caching are definitely important for reducing bandwidth. And on that note, a torrent guide could come in handy! Hosting and seeding torrent files from your vps on the command line is not trivial.

**Comment by storopoli** [comment]
Why not remove just the twitter/facebook seo stuff?

**Comment by mccorxyz** [comment]
I wouldn't mind removing the fb/twitter tags and keeping the bare minimum SEO tags.
I could also see an argument for separating portions of the page into separate pages. One for nginx configuration additions, one for image formats, and one for SEO instead of a general guide to improving web.dev/measure scores.

**Comment by LukeSmithxyz** [comment]
Looks like a good addition, although I might mix and merge some of this with the image minimization guide which is also a PR now.

**Pull request merged**
