### PR TITLE
Align monero and bitcoin images

### PR DESCRIPTION
**Pull request by Cloud11665**
linked issue #55

### CODE REVIEW

**Review by DGKSK8LIFE — CHANGES_REQUESTED** [review]
Can you show a screenshot of the result? Thanks. Also, you may have issues with `<br/>`. Go into your browser's dev tools and test it with a responsive view.

**Comment by Cloud11665** [comment]
> Can you show a screenshot of the result? Thanks. Also, you may have issues with `<br>`. Go into your browser's dev tools and test it with a responsive view.
image

**Comment by DGKSK8LIFE** [comment]
Still not sure if `<br>` is the best long-term solution. Maybe flexbox?

**Comment by Cloud11665** [comment]
isn't flexbox overkill for this? other option would be to use ::before and a mobile media query.

**Pull request closed without merging**
