### PR TITLE
Added a article on how to use cron. 

### PR DESCRIPTION
**Pull request by oidz1234**
Also I have changed links on current pages that mention cron to link to this article.
Hopefully the article is decent, I have tried to take inspiration from other pages but let me know if things need changing.
Thanks!

### CODE REVIEW

**Comment by oidz1234** [comment]
Also, was not sure how to best link this article from the front page so left this up to you.

**Comment by zacharytyhacz** [comment]
I think adding a title with link to this article can go here:

https://github.com/LukeSmithxyz/landchad/blob/master/index.html#L40

That's what the other PR guy did

**Comment by LukeSmithxyz** [comment]
- I think you should include the example command in the first `pre` section as well because as it is now, I don't think many newbies are going to understand what you're talking about there.
- Try to minimize the personal advertisements at the end. Keep it one-line line on based.cooking, e.g.:
```
- Billy Johnshon -- website, youtube, xmr
```

Might be some other tweaks I make after that.

**Comment by oidz1234** [comment]
Ok, I have modified the first pre section, hopefully it helps a bit more. Changed the advertisement as well :)

**Pull request merged**
