### PR TITLE
Added article for Setting Up Nextcloud Instance

### PR DESCRIPTION
**Pull request by MattMadness**
This article provides basic installation instructions for starting a Nextcloud instance alongside an already made Land Chad website. The pull request also includes an update to index.html with the "In the works" entry for Nextcloud removed and the entry for Nextcloud put in the "Excellent Extras" section along with the Nextcloud logo.

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
- Use the `<pre>` tags instead of manually breaking code tags.
- Use `<ul>` for lists...
- Make directions for the root user or wait until there's an article on setting up non-root users and allowing logins.

**Comment by MattMadness** [comment]
I have updated the nextcloud.html file to your specifications.

**Comment by MattMadness** [comment]
Fixed some indention issues. I've just now been introduced to the html `pre` tag, it's actually a gamechanger I used breaks so much!

**Comment by MattMadness** [comment]
Fixed index.html conflict, ready to merge.

**Comment by LukeSmithxyz** [comment]
Going to go ahead and merge this with some tweaks, but I will be double checking everything in several hours to validate it works without too many issues,

**Comment by MattMadness** [comment]
I forgot a few steps and important details, and that's in this pull request (https://github.com/LukeSmithxyz/landchad/pull/18) and it should be up to par, I can't find anything that I forgot. Sorry about that. And of course, feek free to tweak.

**Pull request merged**
