### PR TITLE
Added tutorial for Rainloop Webmail Client

### PR DESCRIPTION
**Pull request by denizat**

### CODE REVIEW

**Comment by tfasano1** [comment]
A self-hosted email tutorial should probably be considered first. Also, I've heard accessing your email through a web interface is less secure. Why not just have a local mail client?

**Comment by denizat** [comment]
Maybe, but this was one of the requested articles in the “On the look out for...” section of the main page. Having an email webclient is useful to have access to email on a machine that you don’t own. You can access your email on any computer or phone with a browser with no additional setup. If you believe the computer is compromised then it will not be secure to look at your email in any way. If you are using https then it should be around the same level of security.

**Comment by tfasano1** [comment]
Ah, I didn't even see that. Fair enough

**Comment by sneedboi888** [comment]
thinking of porting Landchad idea and make it into my own website (as luke might like too because it supports his own idea)

and change things I dislike

**Pull request merged**
