### PR TITLE
Added searx guide.

### PR DESCRIPTION
**Pull request by tenseoverflow**
To save your time, I've made a guide for setting up a Searx instance. This uses Searx's install scripts. It doesn't feature many images but explains the process.
There may be room for some improvement regarding the description, might require more simplicity.

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
There is no information on the site about how to setup and use non-root accounts or with sudo. If you're going to give non-root directions, we'll need an article on that first. Is it not possible to set searx up nowadays with only a root account?

**Comment by tenseoverflow** [comment]
Unfortunately not, that's one of the problems I had setting up searx for the first time, and it wasn't well documented.

I'm guessing this was because of using the /root folder. Maybe something like /usr/local/src would be better, but I haven't tested it.

**Comment by tenseoverflow** [comment]
Yep, does work. The users (searx, morty, filtron) which the install script has to have read access to the searx folder. I'll add the changes to the guide.

**Comment by tenseoverflow** [comment]
Made some last fixes according to the README. You can freely change or merge this branch now.

While I understand your reasoning behind omitting sudo or "$" but I feel like it will cause a lot more confusion later on, especially on these articles where readers may use a completely different setup from your course. Unless using a really minimal setup, there is no point in omitting sudo (maybe politely asking them to `sudo su` before could work) even when root. Oracle's VPS, for instance, already has a sudoer user configured and doesn't use root as default.

This article may very well be the first thing newcomers will see visiting landchad.net from some search engine if they want to know how to set up searx.

Red-pill me on this.

**Pull request closed without merging**
