### PR TITLE
Add Networking

### PR DESCRIPTION
**Pull request by phirecc**
This is a bit of a long one but will serve as prerequisite knowledge to properly understand VPNs, more advanced firewall rules and such. Not exactly sure where to put it on the index page.
I've tried to write it in a way where complete beginners should be able to understand it, let me know if anything needs clarifying.

### CODE REVIEW

**Comment by iamlambda** [comment]
still waiting for the merge. Btw, you could transform your images in text, since it would be more readable, lighter, and would be pastable easily (idk why someone would do it, but you never know)

**Comment by phirecc** [comment]
Yeah no idea why Luke isn't merging this. I used images because the highlighting makes stuff more legible I think and there isn't much reason to copy the text in the images.

**Comment by phirecc** [comment]
@LukeSmithxyz bump?
If you've read it already I'm open to feedback, but I want to write another article on WireGuard and it wouldn't make sense without this one as a prerequisite.

**Comment by LukeSmithxyz** [comment]
I mean, I'm not ruling out adding something like this in the future, but this is just not a tutorial or anything like what everything else on the site is.

**Comment by phirecc** [comment]
I think it would make sense to add another section for more general educational resources separate from the other step-by-step guides, so that guides can link to them for further reading or prerequesite knowledge.

**Comment by LukeSmithxyz** [comment]
I've decided to add all this, images include (although I might do some trimming later). It'll show up on RSS now, and it will appear on the mainpage when I make a system for the other articles to be tagged "concepts."

**Comment by phirecc** [comment]
The formatting of powers has broken in your conversion of the article to 
markdown (for example 10^n became 10n). I also find it harder to read 
now that the inline code blocks aren't green anymore.

**Pull request merged**
