### PR TITLE
How to customize the first digits of your Tor Adress

### PR DESCRIPTION
**Pull request by J053Fabi0**

### CODE REVIEW

**Review by DGKSK8LIFE — APPROVED** [review]

**Comment by tfasano1** [comment]
So you played with some whitespace, and gave the unfathomable advice of turning something off and on again. I get it, but that does not warrant a shout out to your empty website.

**Comment by tfasano1** [comment]
Sorry if I came off mean, thanks for making corrections.

**Comment by J053Fabi0** [comment]
No problem

**Comment by T3SQ8** [comment]
Perhaps it would be more appropriate to add your name in this fashion?
"Minor revisions by ..."
Similarly to the [Rsync](https://landchad.net/rsync.html) article and elsewhere.

**Pull request closed without merging**
